security:
  expiration:
    time-coordenador: 86400000
spring:
  application:
    name: "hallel-api"
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: mongodb+srv://miguel-arcanjo:huLb6nxMTRXPbrQk@hallel-bancodedados.xi3oayc.mongodb.net/?retryWrites=true&w=majority
      database: hallel
springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/api-docs-ui"
    operations-sorter: method
