name: Continuous Integration with Github Actions

on:
  push:
    branches: ["production"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application JAR
      working-directory: ./Api-Hallel
      run: mvn clean package
      
    - name: Docker Compose Build 
      working-directory: ./
      run: docker compose build

    - name: Push to Docker Hub Contianer Registry
      run: | 
        docker tag ${{ secrets.DOCKER_USERNAME }}/api-hallel:latest ${{ secrets.DOCKER_USERNAME }}/api-hallel:${{github.run_id}}
        docker push ${{ secrets.DOCKER_USERNAME }}/api-hallel:${{github.run_id}}
